- name: Get initial dropbear number
  ansible.builtin.shell: |
    uci show dropbear | awk -F '.' '/=dropbear/ {print $2}' | wc -l
  register: inital_dropbear_number

- name: Delete old dropbear records
  ansible.builtin.shell: |
    uci delete dropbear.@dropbear[-1]
  with_sequence: count={{ inital_dropbear_number.stdout }}

- name: Setup dropbear.@dropbear
  ansible.builtin.shell: |
    uci add dropbear dropbear
    uci set dropbear.@dropbear[-1]="{{ item.__type }}"
    uci set dropbear.@dropbear[-1].Port="{{ item.port }}"
    uci set dropbear.@dropbear[-1].Interface="{{ item.interface }}"
    uci set dropbear.@dropbear[-1].PasswordAuth="{{ item.passwordauth }}"
    uci set dropbear.@dropbear[-1].RootPasswordAuth="{{ item.rootpasswordauth }}"

  loop: "{{ dropbear }}"
