- name: Setup all
  hosts: "{{ target | default('router') }}"
  vars_files:
    - vars/dhcp.yml
    - vars/dropbear.yml
    - vars/firewall.yml
    - vars/main.yml
    - vars/network.yml
    - vars/wireless.yml
  roles:
    - { role: bash }
    - { role: wireless }
    - { role: network }
    - { role: dhcp }
    - { role: dropbear }
    - { role: firewall }
    - { role: uhttpd }
    - { role: reboot }
