- name: Setup all
  hosts: "{{ target | default('router') }}"
  vars_files:
    - vars/wireless.yml
    - vars/network.yml
    - vars/dhcp.yml
    - vars/dropbear.yml
  roles:
    - { role: wireless }
    - { role: network }
    - { role: dhcp }
    - { role: dropbear }
  tasks:
    - name: reboot
    - name: restart network-manager
    - name: wait-for
