- name: Preinstall
  delegate_to: localhost
  ansible.builtin.shell: |
    rm -f ./packages/*.ipk
    {% for package in packages %}
      wget -P ./packages {{package.link}}
    {% endfor %}
  register: preinstall_stdout

- name: Print output
  debug: msg={{ preinstall_stdout }}
