# - name: Preinstall
#   delegate_to: localhost
#   ansible.builtin.shell: |
#     rm -f ./packages/*.ipk
#     {% for package in packages %}
#       wget -P ./packages {{package.link}}
#     {% endfor %}
#   register: preinstall_stdout

- name: Prepare folder
  delegate_to: localhost
  file:
    state: "directory"
    path: "./packages"

- name: Clean folder
  delegate_to: localhost
  file:
    state: "absent"
    path: "./packages/{{ item.name }}_{{ arch }}.ipk"
  loop: "{{ packages }}"

- name: Download packages
  delegate_to: localhost
  get_url:
    url: "{{ item.link }}"
    dest: "./packages/{{ item.name }}_{{ arch }}.ipk"
  loop: "{{ packages }}"

# - name: Print output
#   debug: msg={{ preinstall_stdout }}
