- name: Delete old adblock records
  ignore_errors: true
  ansible.builtin.shell: |
    uci delete adblock.global

- name: Setup adblock.@global
  ansible.builtin.shell: |
    uci add adblock {{ item.__name }}
    uci set adblock.{{ item.__name }}="{{ item.__type }}"
    {% for key, value in item.__fields.items() %}
      {% if value.__class__.__name__ == 'list' %}
        {% for _item in value %}
          uci add_list adblock.{{ item.__name }}.{{ key }}="{{ _item }}"
        {% endfor %}
      {% else %}
        uci set adblock.{{ item.__name }}.{{ key }}={{ value }}
      {% endif %}
    {% endfor %}
  loop: "{{ adblock }}"

