- name: Get initial device number
  ansible.builtin.shell: |
    uci show network | awk -F '.' '/=device/ {print $2}' | wc -l
  register: inital_device_number

- name: Delete old device records
  ansible.builtin.shell: |
    uci delete network.@device[-1]
  with_sequence: count={{ inital_device_number.stdout }}

- name: Setup network.@device
  ansible.builtin.shell: |
    uci add network {{ item.__type }}
    uci set network.@{{ item.__type }}[-1]="{{ item.__type }}"
    {% for key, value in item.__fields.items() %}
      {% if value.__class__.__name__ == 'list' %}
        {% for _item in value %}
          uci add_list network.@{{ item.__type }}[-1].{{ key }}="{{ _item }}"
        {% endfor %}
      {% else %}
        uci set network.@{{ item.__type }}[-1].{{ key }}={{ value }}
      {% endif %}
    {% endfor %}
  loop: "{{ network.device }}"
