- name: Get initial device number
  ansible.builtin.shell: |
    uci show network | awk -F '.' '/=device/ {print $2}' | wc -l
  register: inital_device_number

- name: Delete old device records
  ansible.builtin.shell: |
    uci delete network.@device[-1]
  with_sequence: count={{ inital_device_number.stdout }}

- name: Setup network.@device
  ansible.builtin.shell: |
    uci add network device
    uci set network.@device[-1]="{{ item.__type }}"
    {% if item.name is defined %}
      uci set network.@device[-1].name="{{ item.name }}"
    {% endif %}
    {% if item.type is defined %}
      uci set network.@device[-1].type="{{ item.type }}"
    {% endif %}
    {% if item.type is defined %}
      uci set network.@device[-1].type="{{ item.type }}"
    {% endif %}
    {% if item.ports is defined %}
      {% for port in item.ports %}
        uci add_list network.@device[-1].ports="{{ port }}"
      {% endfor %}
    {% endif %}
    {% if item.macaddr is defined %}
      uci set network.@device[-1].macaddr="{{ item.macaddr }}"
    {% endif %}
  loop: "{{ network.device }}"
