- name: Delete old interface records
  ignore_errors: true
  ansible.builtin.shell: |
    uci delete network.vpn | true
    uci delete network.lan | true
    uci delete network.wan | true
    uci delete network.wan6 | true

- name: Setup network.@interface
  ansible.builtin.shell: |
    uci add network {{ item.__name }}
    uci set network.{{ item.__name }}="{{ item.__type }}"
    {% for key, value in item.__fields.items() %}
      {% if value.__class__.__name__ == 'list' %}
        {% for _item in value %}
          uci add_list network.{{ item.__name }}.{{ key }}="{{ _item }}"
        {% endfor %}
      {% else %}
        uci set network.{{ item.__name }}.{{ key }}={{ value }}
      {% endif %}
    {% endfor %}
  loop: "{{ network.interface }}"
