- name: Delete network.wan
  ansible.builtin.shell: |
    uci delete network.wan

- name: Setup network.wan
  ansible.builtin.shell: |
    uci add network wan
    uci set network.wan="{{ network.wan[0].__type }}"
    uci set network.wan.device="{{ network.wan[0].device }}"
    uci set network.wan.proto="{{ network.wan[0].proto }}"
    uci set network.wan.ipaddr="{{ network.wan[0].ipaddr }}"
    uci set network.wan.netmask="{{ network.wan[0].netmask }}"
    uci set network.wan.gateway="{{ network.wan[0].gateway }}"
    {% for dns in network.wan[0].dns %}
      uci add_list network.wan.dns="{{ dns }}"
    {% endfor %}
