- name: Get initial defaults number
  ansible.builtin.shell: |
    uci show firewall | awk -F '.' '/=defaults/ {print $2}' | wc -l
  register: inital_defaults_number

- name: Delete old defaults records
  ansible.builtin.shell: |
    uci delete firewall.@defaults[-1]
  with_sequence: count={{ inital_defaults_number.stdout }}

- name: Setup firewall.@defaults
  ansible.builtin.shell: |
    uci add firewall {{ item.__type }}
    uci set firewall.@{{ item.__type }}[-1]="{{ item.__type }}"
    {% for key, value in item.__fields.items() %}
      {% if value.__class__.__name__ == 'list' %}
        {% for _item in value %}
          uci add_list firewall.@{{ item.__type }}[-1].{{ key }}="{{ _item }}"
        {% endfor %}
      {% else %}
        uci set firewall.@{{ item.__type }}[-1].{{ key }}={{ value }}
      {% endif %}
    {% endfor %}
  loop: "{{ firewall.defaults }}"
