- name: Get initial forwarding number
  ansible.builtin.shell: |
    uci show firewall | awk -F '.' '/=forwarding/ {print $2}' | wc -l
  register: inital_forwarding_number

- name: Delete old forwarding records
  ansible.builtin.shell: |
    uci delete firewall.@forwarding[-1]
  with_sequence: count={{ inital_forwarding_number.stdout }}

- name: Setup firewall.@forwarding
  ansible.builtin.shell: |
    uci add firewall {{ item.__type }}
    uci set firewall.@{{ item.__type }}[-1]="{{ item.__type }}"
    {% for key, value in item.__fields.items() %}
      {% if value.__class__.__name__ == 'list' %}
        {% for _item in value %}
          uci add_list firewall.@{{ item.__type }}[-1].{{ key }}="{{ _item }}"
        {% endfor %}
      {% else %}
        uci set firewall.@{{ item.__type }}[-1].{{ key }}={{ value }}
      {% endif %}
    {% endfor %}
  loop: "{{ firewall.forwarding }}"
