- name: Get initial rule number
  ansible.builtin.shell: |
    uci show firewall | awk -F '.' '/=rule/ {print $2}' | wc -l
  register: inital_rule_number

- name: Delete old rule records
  ansible.builtin.shell: |
    uci delete firewall.@rule[-1]
  with_sequence: count={{ inital_rule_number.stdout }}

- name: Setup firewall.@rule
  ansible.builtin.shell: |
    uci add firewall {{ item.__type }}
    uci set firewall.@{{ item.__type }}[-1]="{{ item.__type }}"
    {% for key, value in item.__fields.items() %}
      {% if value.__class__.__name__ == 'list' %}
        {% for _item in value %}
          uci add_list firewall.@{{ item.__type }}[-1].{{ key }}="{{ _item }}"
        {% endfor %}
      {% else %}
        uci set firewall.@{{ item.__type }}[-1].{{ key }}={{ value }}
      {% endif %}
    {% endfor %}
  loop: "{{ firewall.rule }}"
