- name: Get initial host number
  ansible.builtin.shell: |
    uci show dhcp | awk -F '.' '/=host/ {print $2}'| wc -l
  register: inital_host_number

- name: Delete old host records
  ansible.builtin.shell: |
    uci delete dhcp.@host[-1]
  with_sequence: count={{ inital_host_number.stdout }}

- name: Setup dhcp.@host
  ansible.builtin.shell: |
    uci add dhcp host
    uci set dhcp.@host[-1]="{{ item.__type }}"
    uci set dhcp.@host[-1].name="{{ item.name }}"
    uci set dhcp.@host[-1].mac="{{ item.mac }}"
    uci set dhcp.@host[-1].ip="{{ item.ip }}"
  loop: "{{ dhcp.host }}"

