- name: Delete dhcp.wan
  ansible.builtin.shell: |
    uci delete dhcp.wan

- name: Setup dhcp.wan
  ansible.builtin.shell: |
    uci add dhcp wan
    uci set dhcp.wan="{{ dhcp.wan[0].__type }}"
    uci set dhcp.wan.interface="{{ dhcp.wan[0].interface }}"
    uci set dhcp.wan.start="{{ dhcp.wan[0].start }}"
    uci set dhcp.wan.limit="{{ dhcp.wan[0].limit }}"
    uci set dhcp.wan.leasetime="{{ dhcp.wan[0].leasetime }}"
