- name: Preinstall
  delegate_to: localhost
  ansible.builtin.shell: |
    ssh root@{{ target | default('router') }} 'echo -e "Admin123\nAdmin123" | passwd'
    ssh root@{{ target | default('router') }} 'opkg update'
    ssh root@{{ target | default('router') }} 'opkg install python3'
  register: preinstall_stdout

- name: Print output
  debug: msg={{ preinstall_stdout }}
