- name: Preinstall
  ansible.builtin.shell: |
    {% for package in packages %}
      scp ./packages/{{ package.name }}_{{ arch }}.ipk root@{{ target | default('router') }}:/tmp
      ssh root@{{ target | default('router') }} opkg install /tmp/{{ package.name }}_{{ arch }}.ipk
    {% endfor %}
  register: preinstall_stdout

- name: Print output
  ansible.builtin.debug: msg={{ preinstall_stdout }}
