- name: Make clean workspace
  ansible.builtin.shell: |
    uci revert openvpn
    uci delete openvpn.custom_config | true
    uci delete openvpn.sample_client | true
    uci delete openvpn.sample_server | true
