- name: Add password.auth
  ansible.builtin.lineinfile:
    path: /etc/openvpn/password.auth
    line: "{{ item }}"
    create: true
  loop: "{{ openvpn_credentials }}"
  no_log: true

- name: Copy ProtonVPN config
  ansible.builtin.copy:
    src: ProtonVPN.ovpn
    dest: /etc/openvpn/ProtonVPN.ovpn
    owner: root
    group: root
    mode: 0644
